NewGen.Api/Controllers/ApiPostController.cs
using Microsoft.AspNetCore.Mvc;
using NewGen.DomainModel.Repository;
using System.Collections.Generic;
using NewGen.DomainModel.Models;
using System.Threading.Tasks;
using System;
using System.Linq;
using System.Net;

namespace NewGen.Api.Controllers
{
    [Route("api/[Controller]")]
    public class ApiPostController:Controller 
    {
        private readonly IPostRepository repo;
        public ApiPostController(IPostRepository repo)
        {
            this.repo=repo;
        }

        [HttpGet]
        public IEnumerable<Post> Get()
        {
            return repo.GetAll().Where(x=>x.Id==67).ToList();
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromBody]Post post)
        {
            post.DatePosted=DateTime.Now;
          //  post.Text=WebUtility.HtmlEncode(post.Text);
            await Task.Run(()=>this.repo.Add(post));
            this.repo.Commit();
            return StatusCode(200);
        }
    }
}

NewGen.Api/Controllers/ApiVideoController.cs
using Microsoft.AspNetCore.Mvc;
using NewGen.DomainModel.Repository;
using System.Collections.Generic;
using NewGen.DomainModel.Models;
using System.Threading.Tasks;
using System;
using System.Linq;
using System.Net;

namespace NewGen.Api.Controllers
{
    [Route("api/[Controller]")]
    public class ApiVideoController:Controller 
    {
        private readonly IVideoRepository repo;
        public ApiVideoController(IVideoRepository repo)
        {
            this.repo=repo;
        }

        [HttpGet]
        public IEnumerable<Video> Get()
        {
            return repo.GetAll();
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromBody]Video video)
        {
             video.DatePosted= DateTime.Now;
            await Task.Run(()=>this.repo.Add(video));
            this.repo.Commit();
            return StatusCode(200,video);
        }
    }
}

NewGen.Api/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NewGen.DomainModel.Repository;
using System.Collections.Generic;
using NewGen.DomainModel.Models;
using System.Linq;
using System.Net;

namespace NewGen.Api.Controllers
{
    public class HomeController:Controller 
    {
          [HttpGet]
          public IActionResult Index()
          {
              return View();
          }

          public IActionResult About()
          {
              return View();
          }
    }

}

NewGen.Api/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using NewGen.DomainModel.Repository;
using System.Collections.Generic;
using NewGen.DomainModel.Models;
using System.Linq;
using System.Net;

namespace NewGen.Api.Controllers
{
    public class PostController:Controller 
    {
        private readonly IPostRepository repo;
        public PostController(IPostRepository repo)
        {
            this.repo=repo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

         [HttpGet]
        public IActionResult Details(int Id)
        {
            var item= this.repo.GetAll().Where(x=>x.Id==Id).Single();
             item.Text=WebUtility.HtmlDecode(item.Text);
            return View(item);
        }

        public IActionResult Create()
        {
            return View();
        }
    
       public IActionResult List()
       {
           var list=repo.GetAll();//.Where(x=>x.Id==75).ToList();
           foreach (var item in list)
           {
          item.Text=WebUtility.HtmlDecode(item.Text);
           }
             return View(list);
       }

        [HttpPost]
        public IActionResult Index(Post post)
        {
            this.repo.Add(post);
            this.repo.Commit();
            return View();
        }
    }
}

NewGen.Api/Controllers/SecurityController.cs
using Microsoft.AspNetCore.Mvc;
using NewGen.DomainModel.Repository;
using System.Collections.Generic;
using NewGen.DomainModel.Models;
using System.Linq;
using System.Net;

namespace NewGen.Api.Controllers
{
    public class SecurityController:Controller 
    {
          [HttpGet]
          public IActionResult Index()
          {
              return View();
          }

          [HttpPost]
          public IActionResult Login()
          {
             return RedirectToAction("Create","Post");
          }
    }

}

NewGen.Api/Controllers/VideoController.cs
using Microsoft.AspNetCore.Mvc;
using NewGen.DomainModel.Repository;
using System.Collections.Generic;
using NewGen.DomainModel.Models;
using System.Linq;
using System.Net;

namespace NewGen.Api.Controllers
{
    public class VideoController:Controller 
    {
          private readonly IVideoRepository repo;
          public VideoController(IVideoRepository repo)
          {
                this.repo=repo;
          }

          [HttpGet]
          public IActionResult Index()
          {
              return View();
          }

          [HttpGet]
          public IActionResult List()
          {
              var list=repo.GetAll();
              return View(list);//View(new int[]{1,2,3,4,5});
          }

          [HttpGet]
          public IActionResult Manage()
          {
              return View();
          }

    }

}

NewGen.Api/Views/Post/Create.cshtml
@model Post


@{
    Layout="_LayoutSite";
}
 
<style>
    .panel-default>.panel-heading 
    {
        background-color:none !important;
    }
</style>
<style>
    .page-content-account{
            display: inline-block;
    width: 100%;
    padding: 30px 0 40px 100px;
    }
</style>

   <!--@section header{
        <div class="col-md-12">
                        <h4 class="text-uppercase">New Blog Post</h4>
                        <ol class="breadcrumb">
                            <li><a href="#">Home</a>
                            </li>
                            <li class="active"><a href="#">Blog</a>
                            </li>
                            <li class="active">Blog Listing</li>
                        </ol>
        </div>
   }-->
        <section class="body-content ">

            <div class="page-content-account">
                
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                        <div ng-app="summernoteDemo">
                    <div ng-controller="OptCtrl">
                        <form asp-controller="Post" asp-action="Index" method="post">
                            <div class="row">
                                <div class="col-md-10">
                                    <input type="text" name="Title" ng-model="model.Title" asp-for="Title" class="form-control" placeholder="Title">
                                    <br/>
                                </div>
                            </div>
                            <div>
                                <div class="row">
                                    <div class="col-md-10">
                                        <textarea name="Text" id="" cols="30" config="options" rows="10" summernote name="Text" ng-model="model.Text" asp-for="Text"></textarea>
                                        <!--<summernote ng-model="text"></summernote>-->
                                    </div>
                                </div>
                           
                                <div class="row">
                                    <div class="col-md-10">
                                        <button type="button" ng-click="save()" class="btn btn-primary">Publish This Blog</button>
                                    </div>
            </div>
        </div>
        
     </form>
     
   </div>
</div>

                        </div>
                    
                    </div>
                </div>
            </div>


        </section>
  


       <!--<form asp-controller="Post" asp-action="Index" method="post">
        <input type="text" asp-for="Title">
        <br>
        <textarea asp-for="Text" name="" id="" cols="30" rows="10"></textarea>
      <br>
        <button type="submit">Post</button>
    </form>-->
<!--<div id="summernote">Hello Summernote</div>-->
@section scripts
{
   <script type="text/javascript">
    
    angular.module('summernoteDemo', ['summernote'])
    .controller('OptCtrl', function($scope,$http) {
       $scope.model={};
       $scope.save=function(){
   
              var req = {
            method: 'POST',
            url: '/api/apipost',
            data: $scope.model
            }
 
            $http(req).then(function(data){
                console.log(data);
            },function(err){
                console.log('err',err);
            })
       }
        $scope.enter = function() { console.log('Enter/Return key pressed'); }
        $scope.options = {
        height: 250,
          toolbar: [
    // [groupName, [list of button]]
    ['style', ['style']],
        ['font', ['bold', 'italic', 'underline'/*, 'clear'*/]],
        // ['font', ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'clear']],
        ['fontname', [/* 'fontname'*/]],
        ['fontsize', ['fontsize']],
        ['color', ['color']],
        ['para', [/*'ul', 'ol', 'paragraph'*/]],
        ['height', [/*'height' */]],
        ['table', [/*'table'*/]],
        ['insert', ['link', 'picture', 'hr']],
        ['view', [/*'fullscreen', 'codeview' */]],   // remove codeview button 
        ['help', [/*'help'*/]]
  ]
        // toolbar: [
        //   ['style', ['bold', 'italic', 'underline', 'clear']],
        //   ['fontsize', ['fontsize']],
        //   ['color', ['color']],
        //   ['para', ['ul', 'ol', 'paragraph']],
        //   ['height', ['height']]
        // ]
      };
    })

//     $(document).ready(function() {
//     $('#summernote').summernote({
//             height: 300,
//             lineHeight:2,
//               enterHtml: '<br>',
//         callbacks: {
//     onKeyup: function(e) {
//        // $("#summernote").code()
//       console.log($("#summernote").summernote('code'));
//     },
//      onEnter: function() {

//       var myText = $('#summernote').summernote('isEmpty')? '' : $('#summernote').summernote('code');
//             console.log('Enter/Return key pressed',myText);
//     }
//   }
//     });
//     });

</script>
}

NewGen.Api/Views/Post/Details.cshtml
@model Post
@{
    Layout="_LayoutBlog";
}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=1649371398717173";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>


   <!--classic image post-->
                            <div class="blog-classic">
                                <div class="blog-post">
                                    <div class="full-width">
                                        <img src="~/assets/img/post/p12.jpg" alt="" />
                                    </div>
                                    <h4 class="text-uppercase"><a href="blog-single.html">@Model.Title</a></h4>
                                    <ul class="post-meta">
                                        <li><i class="fa fa-user"></i>posted by <a href="#">admin</a>
                                        </li>
                                        <li><i class="fa fa-folder-open"></i> <a href="#">lifestyle</a>, <a href="#">travel</a>,
                                            <a href="#">fashion</a>
                                        </li>
                                        <li><i class="fa fa-comments"></i> <a href="#">4 comments</a>
                                        </li>
                                    </ul>

                                    <P>
                                        <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Share</a></div>
                                    </P>

                                    <p>
                                        @Html.Raw(Model.Text)
                                    </p>

                                    <!--<p>Lorem ipsum dolor sit amet, consectetur <a href="#">adipisicing elit</a>. Ab adipisci
                                        architecto consequatur debitis eos eum hic illum ipsam itaque laborum magni minima
                                        molestias nostrum numquam odit officia pariatur perspiciatis placeat porro quae rem,
                                        sequi sit soluta temporibus ullam voluptas voluptates. Aliquid amet architecto culpa
                                        cumque eius enim esse eum eveniet ex, fugiat illo ipsum laudantium, minima nemo porro
                                        sequi tempora veritatis vero voluptate, voluptatem. Culpa ducimus est eveniet, iste
                                        iusto officiis quas repudiandae rerum sit tenetur totam voluptas? Accusamus accusantium
                                        alias aliquam aliquid animi commodi dignissimos dolore doloremque dolorum exercitationem
                                        fugiat illum, iste laboriosam maiores molestiae nam odio officia officiis omnis optio
                                        placeat quaerat quia quibusdam quis quo ratione sapiente sed sequi sit tenetur unde
                                        ut veniam voluptas! Dicta, voluptatum!</p>

                                    <div class="blog-post">
                                        <blockquote class="quote-post">
                                            <p>
                                                Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima
                                                rerums unsers sadips amets.. Sed ut perspiciatis unde omnis iste natus error
                                            </p>
                                        </blockquote>
                                    </div>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci at debitis deleniti
                                        dignissimos ea enim iste laboriosam nihil omnis possimus quia, tempora, totam voluptatibus!
                                        Animi consectetur dolor in laboriosam unde.
                                    </p>

                                    <pre>
                                        .blog-classic { margin-bottom: 70px; padding-bottom: 70px; border-bottom: 1px solid #efefef; }
                                    </pre>
                                    <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis
                                        omnis fugats vitaes nemo minima rerums unsers sadips amets.. Sed ut perspiciatis
                                        unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam
                                        rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae
                                        vitae dicta sunt explicabo.</p>-->


                                    <div class="inline-block">

                                        <div class="widget-tags">
                                            <h6 class="text-uppercase">Tags </h6>
                                            <a href="">Portfolio</a>
                                            <a href="">Design</a>
                                            <a href="">Link</a>
                                            <a href="">Gallery</a>
                                            <a href="">Video</a>
                                            <a href="">Clean</a>
                                            <a href="">Retina</a>
                                        </div>
                                    </div>


                                    <div class="clearfix inline-block m-top-50 m-bot-50">
                                        <h6 class="text-uppercase">Share this Post </h6>
                                        <div class="widget-social-link circle">
                                            <a href="#"><i class="fa fa-facebook"></i></a>
                                            <a href="#"><i class="fa fa-twitter"></i></a>
                                            <a href="#"><i class="fa fa-dribbble"></i></a>
                                            <a href="#"><i class="fa fa-google-plus"></i></a>
                                            <a href="#"><i class="fa fa-behance"></i></a>
                                        </div>
                                    </div>


                                    <div class="pagination-row">

                                        <div class="pagination-post">
                                            <div class="prev-post">
                                                <a href="#">
                                                    <div class="arrow">
                                                        <i class="fa fa-angle-double-left"></i>
                                                    </div>
                                                    <div class="pagination-txt">
                                                        <span>Previous Post</span>
                                                    </div>
                                                </a>
                                            </div>

                                            <div class="post-list-link">
                                                <a href="#">
                                                    <i class="fa fa-home"></i>
                                                </a>
                                            </div>

                                            <div class="next-post">
                                                <a href="#">
                                                    <div class="arrow">
                                                        <i class="fa fa-angle-double-right"></i>
                                                    </div>
                                                    <div class="pagination-txt">
                                                        <span>Next Post</span>
                                                    </div>
                                                </a>
                                            </div>

                                        </div>

                                    </div>


                                    <!--comments discussion section start-->


                                    <!--comments  section end-->



                                </div>
                            </div>
                            <!--classic image post-->

NewGen.Api/Views/Post/List.cshtml
@model IEnumerable<Post>
@using System.Net

@{
    Layout="_LayoutBlog";
}

                   <div >
                            @foreach(var blog in Model)
                            {
                             <div class="blog-classic">
                                <div class="date">
                                    24
                                    <span>MAR 2015</span>
                                </div>
                                <div class="blog-post">
                                    <div class="full-width">
                                        <img src="~/assets/img/post/p12.jpg" alt="" />
                                    </div>
                                    <h4 class="text-uppercase"><a href="blog-single.html">standard blog post with photo</a></h4>
                                    <ul class="post-meta">
                                        <li><i class="fa fa-user"></i>posted by <a href="#">admin</a>
                                        </li>
                                        <li><i class="fa fa-folder-open"></i>  <a href="#">lifestyle</a>, <a href="#">travel</a>, <a href="#">fashion</a>
                                        </li>
                                        <li><i class="fa fa-comments"></i>  <a href="#">4 comments</a>
                                        </li>
                                    </ul>
                                    <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets.. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
                                        doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                                    <a href="/Post/Details/@blog.Id" class="btn btn-small btn-dark-solid  "> Continue Reading @blog.Id</a>
                             
                                </div>
                            </div>
                            }
                       


                            <!--pagination-->
                            <div class="text-center">
                                <ul class="pagination custom-pagination">
                                    <li><a href="#">Prev</a>
                                    </li>
                                    <li class="active"><a href="#">1</a>
                                    </li>
                                    <li><a href="#">2</a>
                                    </li>
                                    <li><a href="#">3</a>
                                    </li>
                                    <li><a href="#">4</a>
                                    </li>
                                    <li><a href="#">5</a>
                                    </li>
                                    <li><a href="#">Next</a>
                                    </li>
                                </ul>
                            </div>
                            <!--pagination-->
                   </div>

NewGen.Api/Views/Security/Index.cshtml
@{
    Layout="_LayoutSecurity";
}



<div class="container">
      <div class="row">
          <div class="col-md-6 col-md-offset-3 panel-container">
                 <div class="panel panel-default account">
                  <div class="panel-heading">
                    <h3 class="panel-title">Sign In to Your Account</h3>
                  </div>
                    <div class="panel-body">
                            <form asp-controller="Security" asp-action="Login" method="Post">
                                    <div class="row">
                                        <div class="col-md-7">
                                            <div>
                                              <label for="">Email</label>
                                            </div>
                                            <input type="text" placeholer="your email" class="form-control" >
                                        </div>
                                    </div> 
                                    <div class="row">
                                        <div class="col-md-7">
                                            <div>
                                              <label for="">Password</label>
                                            </div>
                                            <input type="password" placeholer="your password" class="form-control" >
                                        </div>
                                    </div> 
                                    <div class="row">
                                        <div class="col-md-7">
                                           <br>
                                            <input type="submit" value="Sign In" class="btn btn-primary">
                                        </div>
                                    </div> 
                            </form>
                    </div>
                  </div>
          </div>
      </div>
</div>

    

NewGen.Api/Views/Shared/_LayoutBlogRoot.cshtml
@{
    Layout="_LayoutSite";
}
   @section header{
        <div class="col-md-12">
                        <h4 class="text-uppercase">Blog Listing</h4>
                        <ol class="breadcrumb">
                            <li><a href="#">Home</a>
                            </li>
                            <li class="active"><a href="#">Blog</a>
                            </li>
                            <li class="active">Blog Listing</li>
                        </ol>
        </div>
   }
          <div class="page-content">
                <div class="container">
                    <div class="row">
                       <div class="col-md-8">
                               @RenderBody()
                       </div>
                       <div class="col-md-4">
                             @RenderSection("right",required:false)
                       </div>
                    </div>
                </div>
          </div>


        

NewGen.Api/Views/Shared/_LayoutIndexRoot.cshtml
@{
    Layout="_LayoutSite";
}
   @section header{
        <div class="col-md-12">
                        <h4 class="text-uppercase">Blog Listing</h4>
                        <ol class="breadcrumb">
                            <li><a href="#">Home</a>
                            </li>
                            <li class="active"><a href="#">Blog</a>
                            </li>
                            <li class="active">Blog Listing</li>
                        </ol>
        </div>
   }

      <section class="body-content magazine-grid p-top-50">
            <!--breaking news-->
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="magazine-latest-news">
                                <div class="container">
                                    <div class="breaking">
                                        Breaking News
                                    </div>
                                    <div class="news-slider">
                                        
                                    <div class="flex-viewport" style="overflow: hidden; position: relative;"><ul class="slides" style="width: 1000%; transition-duration: 0.6s; transform: translate3d(-2580px, 0px, 0px);"><li class="clone" aria-hidden="true" style="width: 860px; float: left; display: block;">
                                                <a href="#">Inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</a>
                                            </li>
                                            <li class="" style="width: 860px; float: left; display: block;">
                                                <a href="#">Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis</a>
                                            </li>
                                            <li class="" style="width: 860px; float: left; display: block;">
                                                <a href="#">Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes</a>
                                            </li>
                                            <li class="flex-active-slide" style="width: 860px; float: left; display: block;">
                                                <a href="#">Inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</a>
                                            </li>
                                        <li class="clone" aria-hidden="true" style="width: 860px; float: left; display: block;">
                                                <a href="#">Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis</a>
                                            </li></ul></div><ol class="flex-control-nav flex-control-paging"><li><a class="">1</a></li><li><a class="">2</a></li><li><a class="flex-active">3</a></li></ol><ul class="flex-direction-nav"><li class="flex-nav-prev"><a class="flex-prev" href="#">Previous</a></li><li class="flex-nav-next"><a class="flex-next" href="#">Next</a></li></ul></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <!--breaking news-->
             
             <div class="page-content-sm">
                <div class="container">
                    <div class="row">
                            <div class="col-md-9">
                        
                         @RenderBody()
                        </div>
                      <div class="col-md-3">
                            @RenderSection("right",required:false)
                      </div>
   
                    </div>
                </div>
            </div>

        </section>

NewGen.Api/Views/Shared/_LayoutSecurity.cshtml
@{
    Layout="_LayoutRoot";
}

<div class="page-background">
   @RenderBody()
</div>

NewGen.Api/Views/Shared/_LayoutVideo.cshtml
@{
    Layout="_LayoutVideoRoot";
}


   @RenderBody()

NewGen.Api/Views/Shared/_LayoutVideoRoot.cshtml
@{
    Layout="_LayoutSite";
}
   @section header{
        <div class="col-md-12">
                        <h4 class="text-uppercase">Blog Listing</h4>
                        <ol class="breadcrumb">
                            <li><a href="#">Home</a>
                            </li>
                            <li class="active"><a href="#">Blog</a>
                            </li>
                            <li class="active">Blog Listing</li>
                        </ol>
        </div>
   }

                            
<div class="page-background">
   @RenderBody()
</div>
                  
                     
           


        